fortune:
  fallbackFortune: Today is your lucky day!

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://fortune-eureka.cfapps.io/eureka/
